### ISSUE TITLE
about AgentManager

### ISSUE THREAD

**Issue by ddbXJ** [Will1229/Blockchain#2]
I have a question :  

In this demo, we have an `AgentManager`, to create an `Agent`(`peer`), also we tell this new agent all the existed agents.

In fact, we don't have a manager to do such things. Each peer try to connect to a known peer, or try to connect to a peer it had connected before.

Can these connected things be doing by`Agent` itself, not by `AgentManager`? (in this proj)

**Comment by Will1229** [comment]
Precisely. In this project the Agent manager is kind of center node in the network which mantains all the exsiting agents (or nodes, or peers). This is to simplify the implementation and make it easier to demostrate the blockchain concept in a "centralised" user interface.

In real world I think some kind of peer discovery will be needed for agents to find each other. It could be a preset domain name list in every newly created agent so that the new agent can resolve a bunch of ip address of exsiting peers by talking to DNS. And then get more peers from other agents. An agent doesn't need to know all the other agents in the network. In this case agent manager provides kind of similar function there.
